services:
  # Backend API service
  - type: web
    name: mutual-funds-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && PYTHONPATH=$PYTHONPATH:. gunicorn run:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: API_1_URL
        value: https://groww.in/v1/api/search/v3/query/global/st_p_query?entity_type=Scheme&page=0&size=10000
      - key: API_2_TEMPLATE
        value: https://groww.in/v1/api/data/mf/web/v4/scheme/search/{search_id}
      - key: DATABASE_URL
        fromDatabase:
          name: mutual-funds-db
          property: connectionString

  # Frontend service
  - type: web
    name: mutual-funds-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: mutual-funds-db
    plan: free